package common

import (
	"log"
	"reflect"
)

var prlKeycode2ScanCode [256][]uint = [256][]uint{
	/* Index 0   - PRL_KEY_INVALID                          */ {},
	/* Index 1   - PRL_KEY_WILDCARD_ANY                     */ {},
	/* Index 2   - PRL_KEY_WILDCARD_KEYBOARD                */ {},
	/* Index 3   - PRL_KEY_WILDCARD_MOUSE                   */ {},
	/* Index 4   - PRL_KEY_WILDCARD_SHIFT                   */ {},
	/* Index 5   - PRL_KEY_WILDCARD_CTRL                    */ {},
	/* Index 6   - PRL_KEY_WILDCARD_ALT                     */ {},
	/* Index 7   - PRL_KEY_WILDCARD_WIN                     */ {},
	/* Index 8   - PRL_KEY_INVALID                          */ {},
	/* Index 9   - PRL_KEY_ESCAPE                           */ {0x01},
	/* Index 10  - PRL_KEY_1                                */ {0x02},
	/* Index 11  - PRL_KEY_2                                */ {0x03},
	/* Index 12  - PRL_KEY_3                                */ {0x04},
	/* Index 13  - PRL_KEY_4                                */ {0x05},
	/* Index 14  - PRL_KEY_5                                */ {0x06},
	/* Index 15  - PRL_KEY_6                                */ {0x07},
	/* Index 16  - PRL_KEY_7                                */ {0x08},
	/* Index 17  - PRL_KEY_8                                */ {0x09},
	/* Index 18  - PRL_KEY_9                                */ {0x0A},
	/* Index 19  - PRL_KEY_0                                */ {0x0B},
	/* Index 20  - PRL_KEY_MINUS                            */ {0x0C},
	/* Index 21  - PRL_KEY_EQUAL                            */ {0x0D},
	/* Index 22  - PRL_KEY_BACKSPACE                        */ {0x0E},
	/* Index 23  - PRL_KEY_TAB                              */ {0x0F},
	/* Index 24  - PRL_KEY_Q                                */ {0x10},
	/* Index 25  - PRL_KEY_W                                */ {0x11},
	/* Index 26  - PRL_KEY_E                                */ {0x12},
	/* Index 27  - PRL_KEY_R                                */ {0x13},
	/* Index 28  - PRL_KEY_T                                */ {0x14},
	/* Index 29  - PRL_KEY_Y                                */ {0x15},
	/* Index 30  - PRL_KEY_U                                */ {0x16},
	/* Index 31  - PRL_KEY_I                                */ {0x17},
	/* Index 32  - PRL_KEY_O                                */ {0x18},
	/* Index 33  - PRL_KEY_P                                */ {0x19},
	/* Index 34  - PRL_KEY_LEFT_BRACKET                     */ {0x1A},
	/* Index 35  - PRL_KEY_RIGHT_BRACKET                    */ {0x1B},
	/* Index 36  - PRL_KEY_ENTER                            */ {0x1C},
	/* Index 37  - PRL_KEY_LEFT_CONTROL                     */ {0x1D},
	/* Index 38  - PRL_KEY_A                                */ {0x1E},
	/* Index 39  - PRL_KEY_S                                */ {0x1F},
	/* Index 40  - PRL_KEY_D                                */ {0x20},
	/* Index 41  - PRL_KEY_F                                */ {0x21},
	/* Index 42  - PRL_KEY_G                                */ {0x22},
	/* Index 43  - PRL_KEY_H                                */ {0x23},
	/* Index 44  - PRL_KEY_J                                */ {0x24},
	/* Index 45  - PRL_KEY_K                                */ {0x25},
	/* Index 46  - PRL_KEY_L                                */ {0x26},
	/* Index 47  - PRL_KEY_SEMICOLON                        */ {0x27},
	/* Index 48  - PRL_KEY_QUOTE                            */ {0x28},
	/* Index 49  - PRL_KEY_TILDA                            */ {0x29},
	/* Index 50  - PRL_KEY_LEFT_SHIFT                       */ {0x2A},
	/* Index 51  - PRL_KEY_BACKSLASH                        */ {0x2B},
	/* Index 52  - PRL_KEY_Z                                */ {0x2C},
	/* Index 53  - PRL_KEY_X                                */ {0x2D},
	/* Index 54  - PRL_KEY_C                                */ {0x2E},
	/* Index 55  - PRL_KEY_V                                */ {0x2F},
	/* Index 56  - PRL_KEY_B                                */ {0x30},
	/* Index 57  - PRL_KEY_N                                */ {0x31},
	/* Index 58  - PRL_KEY_M                                */ {0x32},
	/* Index 59  - PRL_KEY_COMMA                            */ {0x33},
	/* Index 60  - PRL_KEY_DOT                              */ {0x34},
	/* Index 61  - PRL_KEY_SLASH                            */ {0x35},
	/* Index 62  - PRL_KEY_RIGHT_SHIFT                      */ {0x36},
	/* Index 63  - PRL_KEY_NP_STAR                          */ {0x37},
	/* Index 64  - PRL_KEY_LEFT_ALT                         */ {0x38},
	/* Index 65  - PRL_KEY_SPACE                            */ {0x39},
	/* Index 66  - PRL_KEY_CAPS_LOCK                        */ {0x3A},
	/* Index 67  - PRL_KEY_F1                               */ {0x3B},
	/* Index 68  - PRL_KEY_F2                               */ {0x3C},
	/* Index 69  - PRL_KEY_F3                               */ {0x3D},
	/* Index 70  - PRL_KEY_F4                               */ {0x3E},
	/* Index 71  - PRL_KEY_F5                               */ {0x3F},
	/* Index 72  - PRL_KEY_F6                               */ {0x40},
	/* Index 73  - PRL_KEY_F7                               */ {0x41},
	/* Index 74  - PRL_KEY_F8                               */ {0x42},
	/* Index 75  - PRL_KEY_F9                               */ {0x43},
	/* Index 76  - PRL_KEY_F10                              */ {0x44},
	/* Index 77  - PRL_KEY_NUM_LOCK                         */ {0x45},
	/* Index 78  - PRL_KEY_SCROLL_LOCK                      */ {0x46},
	/* Index 79  - PRL_KEY_NP_7                             */ {0x47},
	/* Index 80  - PRL_KEY_NP_8                             */ {0x48},
	/* Index 81  - PRL_KEY_NP_9                             */ {0x49},
	/* Index 82  - PRL_KEY_NP_MINUS                         */ {0x4A},
	/* Index 83  - PRL_KEY_NP_4                             */ {0x4B},
	/* Index 84  - PRL_KEY_NP_5                             */ {0x4C},
	/* Index 85  - PRL_KEY_NP_6                             */ {0x4D},
	/* Index 86  - PRL_KEY_NP_PLUS                          */ {0x4E},
	/* Index 87  - PRL_KEY_NP_1                             */ {0x4F},
	/* Index 88  - PRL_KEY_NP_2                             */ {0x50},
	/* Index 89  - PRL_KEY_NP_3                             */ {0x51},
	/* Index 90  - PRL_KEY_NP_0                             */ {0x52},
	/* Index 91  - PRL_KEY_NP_DELETE                        */ {0x53},
	/* Index 92  - PRL_KEY_PRINT                            */ {0xE0, 0x2A, 0xE0, 0x37},
	/* Index 93  - PRL_KEY_EUROPE_1                         */ {0x2B},
	/* Index 94  - PRL_KEY_EUROPE_2                         */ {0x56},
	/* Index 95  - PRL_KEY_F11                              */ {0x57},
	/* Index 96  - PRL_KEY_F12                              */ {0x58},
	/* Index 97  - PRL_KEY_HOME                             */ {0xE0, 0x47},
	/* Index 98  - PRL_KEY_UP                               */ {0xE0, 0x48},
	/* Index 99  - PRL_KEY_PAGE_UP                          */ {0xE0, 0x49},
	/* Index 100 - PRL_KEY_LEFT                             */ {0xE0, 0x4B},
	/* Index 101 - PRL_KEY_INVALID                          */ {},
	/* Index 102 - PRL_KEY_RIGHT                            */ {0xE0, 0x4D},
	/* Index 103 - PRL_KEY_END                              */ {0xE0, 0x4F},
	/* Index 104 - PRL_KEY_DOWN                             */ {0xE0, 0x50},
	/* Index 105 - PRL_KEY_PAGE_DOWN                        */ {0xE0, 0x51},
	/* Index 106 - PRL_KEY_INSERT                           */ {0xE0, 0x52},
	/* Index 107 - PRL_KEY_DELETE                           */ {0xE0, 0x53},
	/* Index 108 - PRL_KEY_NP_ENTER                         */ {0xE0, 0x1C},
	/* Index 109 - PRL_KEY_RIGHT_CONTROL                    */ {0xE0, 0x1D},
	/* Index 110 - PRL_KEY_PAUSE                            */ {0xE1, 0x1D, 0x45, 0xE1, 0x9D, 0xC5},
	/* Index 111 - PRL_KEY_INVALID                          */ {},
	/* Index 112 - PRL_KEY_NP_SLASH                         */ {0xE0, 0x35},
	/* Index 113 - PRL_KEY_RIGHT_ALT                        */ {0xE0, 0x38},
	/* Index 114 - PRL_KEY_INVALID                          */ {},
	/* Index 115 - PRL_KEY_LEFT_WIN                         */ {0xE0, 0x5B},
	/* Index 116 - PRL_KEY_RIGHT_WIN                        */ {0xE0, 0x5C},
	/* Index 117 - PRL_KEY_MENU                             */ {0xE0, 0x5D},
	/* Index 118 - PRL_KEY_MEDIA_NEXT_TRACK                 */ {0xE0, 0x19},
	/* Index 119 - PRL_KEY_MEDIA_PREV_TRACK                 */ {0xE0, 0x10},
	/* Index 120 - PRL_KEY_MEDIA_STOP                       */ {0xE0, 0x24},
	/* Index 121 - PRL_KEY_MEDIA_PLAY_PAUSE                 */ {0xE0, 0x22},
	/* Index 122 - PRL_KEY_MUTE                             */ {0xE0, 0x20},
	/* Index 123 - PRL_KEY_VOLUME_UP                        */ {0xE0, 0x30},
	/* Index 124 - PRL_KEY_VOLUME_DOWN                      */ {0xE0, 0x2E},
	/* Index 125 - PRL_KEY_MEDIA_SELECT                     */ {0xE0, 0x6D},
	/* Index 126 - PRL_KEY_APP_MAIL                         */ {0xE0, 0x6C},
	/* Index 127 - PRL_KEY_APP_CALCULATOR                   */ {0xE0, 0x21},
	/* Index 128 - PRL_KEY_APP_MY_COMPUTER                  */ {0xE0, 0x6B},
	/* Index 129 - PRL_KEY_WWW_SEARCH                       */ {0xE0, 0x65},
	/* Index 130 - PRL_KEY_WWW_HOME                         */ {0xE0, 0x32},
	/* Index 131 - PRL_KEY_WWW_BACK                         */ {0xE0, 0x6A},
	/* Index 132 - PRL_KEY_WWW_FORWARD                      */ {0xE0, 0x69},
	/* Index 133 - PRL_KEY_WWW_STOP                         */ {0xE0, 0x68},
	/* Index 134 - PRL_KEY_WWW_REFRESH                      */ {0xE0, 0x67},
	/* Index 135 - PRL_KEY_WWW_FAVORITES                    */ {0xE0, 0x66},
	/* Index 136 - PRL_KEY_EJECT                            */ {0xE0, 0x63},
	/* Index 137 - PRL_KEY_SYSTEM_POWER                     */ {0xE0, 0x5E},
	/* Index 138 - PRL_KEY_SYSTEM_SLEEP                     */ {0xE0, 0x5F},
	/* Index 139 - PRL_KEY_SYSTEM_WAKE                      */ {0xE0, 0x63},
	/* Index 140 - PRL_KEY_BRAZILIAN_KEYPAD                 */ {0x7E},
	/* Index 141 - PRL_KEY_RO                               */ {0x73},
	/* Index 142 - PRL_KEY_HIRAGANA_KATAKANA                */ {0x70},
	/* Index 143 - PRL_KEY_YEN                              */ {0x7D},
	/* Index 144 - PRL_KEY_HENKAN                           */ {0x79},
	/* Index 145 - PRL_KEY_MUHENKAN                         */ {0x7B},
	/* Index 146 - PRL_KEY_PC9800_KEYPAD                    */ {0x5C},
	/* Index 147 - PRL_KEY_HANGUEL                          */ {0xF2},
	/* Index 148 - PRL_KEY_HANJA                            */ {0xF1},
	/* Index 149 - PRL_KEY_KATAKANA                         */ {0x78},
	/* Index 150 - PRL_KEY_HIRAGANA                         */ {0x77},
	/* Index 151 - PRL_KEY_ZENKAKU_HANKAKU                  */ {0x76},
	/* Index 152 - PRL_KEY_F13                              */ {0x64},
	/* Index 153 - PRL_KEY_F14                              */ {0x65},
	/* Index 154 - PRL_KEY_F15                              */ {0x66},
	/* Index 155 - PRL_KEY_F16                              */ {0x67},
	/* Index 156 - PRL_KEY_F17                              */ {0x68},
	/* Index 157 - PRL_KEY_F18                              */ {0x69},
	/* Index 158 - PRL_KEY_F19                              */ {0x6A},
	/* Index 159 - PRL_KEY_F20                              */ {0x6B},
	/* Index 160 - PRL_KEY_F21                              */ {0x6C},
	/* Index 161 - PRL_KEY_F22                              */ {0x6D},
	/* Index 162 - PRL_KEY_F23                              */ {0x6E},
	/* Index 163 - PRL_KEY_F24                              */ {0x76},
	/* Index 164 - PRL_KEY_NP_EQUAL                         */ {0x59},
	/* Index 165 - PRL_KEY_BREAK                            */ {0xE0, 0x46, 0xE0, 0xC6},
	/* Index 166 - PRL_KEY_PRINT_WITH_MODIFIER              */ {0xE0, 0x37},
	/* Index 167 - PRL_KEY_SYSRQ                            */ {0x54},
	/* Index 168 - PRL_KEY_FN                               */ {},
	/* Index 169 - PRL_KEY_EURO                             */ {0xE0, 0x33},
	/* Index 170 - PRL_KEY_DOLLAR                           */ {0xE0, 0x34},
	/* Index 171 - PRL_KEY_MON_BRIGHTNESS_DOWN              */ {},
	/* Index 172 - PRL_KEY_MON_BRIGHTNESS_UP                */ {},
	/* Index 173 - PRL_KEY_APP_EXPOSE                       */ {},
	/* Index 174 - PRL_KEY_APP_DASHBOARD                    */ {},
	/* Index 175 - PRL_KEY_KBD_BRIGHTNESS_DOWN              */ {},
	/* Index 176 - PRL_KEY_KBD_BRIGHTNESS_UP                */ {},
	/* Index 177 - PRL_KEY_MAC129                           */ {},
	/* Index 178 - PRL_KEY_LEFT_BUTTON                      */ {},
	/* Index 179 - PRL_KEY_MIDDLE_BUTTON                    */ {},
	/* Index 180 - PRL_KEY_RIGHT_BUTTON                     */ {},
	/* Index 181 - PRL_KEY_MOVE_UP_LEFT                     */ {},
	/* Index 182 - PRL_KEY_MOVE_UP                          */ {},
	/* Index 183 - PRL_KEY_MOVE_UP_RIGHT                    */ {},
	/* Index 184 - PRL_KEY_MOVE_LEFT                        */ {},
	/* Index 185 - PRL_KEY_MOVE_RIGHT                       */ {},
	/* Index 186 - PRL_KEY_MOVE_DOWN_LEFT                   */ {},
	/* Index 187 - PRL_KEY_MOVE_DOWN                        */ {},
	/* Index 188 - PRL_KEY_MOVE_DOWN_RIGHT                  */ {},
	/* Index 189 - PRL_KEY_WHEEL_UP                         */ {},
	/* Index 190 - PRL_KEY_WHEEL_DOWN                       */ {},
	/* Index 191 - PRL_KEY_WHEEL_LEFT                       */ {},
	/* Index 192 - PRL_KEY_WHEEL_RIGHT                      */ {},
	/* Index 193 - PRL_KEY_INVALID                          */ {},
	/* Index 194 - PRL_KEY_INVALID                          */ {},
	/* Index 195 - PRL_KEY_INVALID                          */ {},
	/* Index 196 - PRL_KEY_INVALID                          */ {},
	/* Index 197 - PRL_KEY_INVALID                          */ {},
	/* Index 198 - PRL_KEY_INVALID                          */ {},
	/* Index 199 - PRL_KEY_INVALID                          */ {},
	/* Index 200 - PRL_KEY_INVALID                          */ {},
	/* Index 201 - PRL_KEY_INVALID                          */ {},
	/* Index 202 - PRL_KEY_INVALID                          */ {},
	/* Index 203 - PRL_KEY_INVALID                          */ {},
	/* Index 204 - PRL_KEY_INVALID                          */ {},
	/* Index 205 - PRL_KEY_INVALID                          */ {},
	/* Index 206 - PRL_KEY_INVALID                          */ {},
	/* Index 207 - PRL_KEY_INVALID                          */ {},
	/* Index 208 - PRL_KEY_INVALID                          */ {},
	/* Index 209 - PRL_KEY_INVALID                          */ {},
	/* Index 210 - PRL_KEY_INVALID                          */ {},
	/* Index 211 - PRL_KEY_INVALID                          */ {},
	/* Index 212 - PRL_KEY_INVALID                          */ {},
	/* Index 213 - PRL_KEY_INVALID                          */ {},
	/* Index 214 - PRL_KEY_INVALID                          */ {},
	/* Index 215 - PRL_KEY_INVALID                          */ {},
	/* Index 216 - PRL_KEY_INVALID                          */ {},
	/* Index 217 - PRL_KEY_INVALID                          */ {},
	/* Index 218 - PRL_KEY_INVALID                          */ {},
	/* Index 219 - PRL_KEY_INVALID                          */ {},
	/* Index 220 - PRL_KEY_INVALID                          */ {},
	/* Index 221 - PRL_KEY_INVALID                          */ {},
	/* Index 222 - PRL_KEY_INVALID                          */ {},
	/* Index 223 - PRL_KEY_INVALID                          */ {},
	/* Index 224 - PRL_KEY_INVALID                          */ {},
	/* Index 225 - PRL_KEY_INVALID                          */ {},
	/* Index 226 - PRL_KEY_INVALID                          */ {},
	/* Index 227 - PRL_KEY_INVALID                          */ {},
	/* Index 228 - PRL_KEY_INVALID                          */ {},
	/* Index 229 - PRL_KEY_INVALID                          */ {},
	/* Index 230 - PRL_KEY_INVALID                          */ {},
	/* Index 231 - PRL_KEY_INVALID                          */ {},
	/* Index 232 - PRL_KEY_INVALID                          */ {},
	/* Index 233 - PRL_KEY_INVALID                          */ {},
	/* Index 234 - PRL_KEY_INVALID                          */ {},
	/* Index 235 - PRL_KEY_INVALID                          */ {},
	/* Index 236 - PRL_KEY_INVALID                          */ {},
	/* Index 237 - PRL_KEY_INVALID                          */ {},
	/* Index 238 - PRL_KEY_INVALID                          */ {},
	/* Index 239 - PRL_KEY_INVALID                          */ {},
	/* Index 240 - PRL_KEY_INVALID                          */ {},
	/* Index 241 - PRL_KEY_INVALID                          */ {},
	/* Index 242 - PRL_KEY_INVALID                          */ {},
	/* Index 243 - PRL_KEY_INVALID                          */ {},
	/* Index 244 - PRL_KEY_INVALID                          */ {},
	/* Index 245 - PRL_KEY_INVALID                          */ {},
	/* Index 246 - PRL_KEY_INVALID                          */ {},
	/* Index 247 - PRL_KEY_INVALID                          */ {},
	/* Index 248 - PRL_KEY_INVALID                          */ {},
	/* Index 249 - PRL_KEY_INVALID                          */ {},
	/* Index 250 - PRL_KEY_INVALID                          */ {},
	/* Index 251 - PRL_KEY_INVALID                          */ {},
	/* Index 252 - PRL_KEY_INVALID                          */ {},
	/* Index 253 - PRL_KEY_INVALID                          */ {},
	/* Index 254 - PRL_KEY_INVALID                          */ {},
	/* Index 255 - PRL_KEY_INVALID                          */ {},
}

func getKeycodeFromScanCode(scanCode []uint) int {
	for i, sc := range prlKeycode2ScanCode {
		if reflect.DeepEqual(sc, scanCode) {
			return i
		}
	}
	log.Println("No match found for scancode", scanCode)
	return 0
}
